// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prof_dag.proto

#ifndef PROTOBUF_prof_5fdag_2eproto__INCLUDED
#define PROTOBUF_prof_5fdag_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace caffe2 {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_prof_5fdag_2eproto();
void protobuf_AssignDesc_prof_5fdag_2eproto();
void protobuf_ShutdownFile_prof_5fdag_2eproto();

class BlobProfile;
class ProfDAGProto;
class ProfDAGProtos;
class TwoNumberStatsProto;

// ===================================================================

class TwoNumberStatsProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe2.TwoNumberStatsProto) */ {
 public:
  TwoNumberStatsProto();
  virtual ~TwoNumberStatsProto();

  TwoNumberStatsProto(const TwoNumberStatsProto& from);

  inline TwoNumberStatsProto& operator=(const TwoNumberStatsProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TwoNumberStatsProto& default_instance();

  void Swap(TwoNumberStatsProto* other);

  // implements Message ----------------------------------------------

  inline TwoNumberStatsProto* New() const { return New(NULL); }

  TwoNumberStatsProto* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TwoNumberStatsProto& from);
  void MergeFrom(const TwoNumberStatsProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TwoNumberStatsProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float mean = 1;
  bool has_mean() const;
  void clear_mean();
  static const int kMeanFieldNumber = 1;
  float mean() const;
  void set_mean(float value);

  // optional float stddev = 2;
  bool has_stddev() const;
  void clear_stddev();
  static const int kStddevFieldNumber = 2;
  float stddev() const;
  void set_stddev(float value);

  // optional int64 count = 3;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 3;
  ::google::protobuf::int64 count() const;
  void set_count(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:caffe2.TwoNumberStatsProto)
 private:
  inline void set_has_mean();
  inline void clear_has_mean();
  inline void set_has_stddev();
  inline void clear_has_stddev();
  inline void set_has_count();
  inline void clear_has_count();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float mean_;
  float stddev_;
  ::google::protobuf::int64 count_;
  friend void  protobuf_AddDesc_prof_5fdag_2eproto();
  friend void protobuf_AssignDesc_prof_5fdag_2eproto();
  friend void protobuf_ShutdownFile_prof_5fdag_2eproto();

  void InitAsDefaultInstance();
  static TwoNumberStatsProto* default_instance_;
};
// -------------------------------------------------------------------

class BlobProfile : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe2.BlobProfile) */ {
 public:
  BlobProfile();
  virtual ~BlobProfile();

  BlobProfile(const BlobProfile& from);

  inline BlobProfile& operator=(const BlobProfile& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BlobProfile& default_instance();

  void Swap(BlobProfile* other);

  // implements Message ----------------------------------------------

  inline BlobProfile* New() const { return New(NULL); }

  BlobProfile* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BlobProfile& from);
  void MergeFrom(const BlobProfile& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BlobProfile* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .caffe2.TwoNumberStatsProto bytes_used = 3;
  bool has_bytes_used() const;
  void clear_bytes_used();
  static const int kBytesUsedFieldNumber = 3;
  const ::caffe2::TwoNumberStatsProto& bytes_used() const;
  ::caffe2::TwoNumberStatsProto* mutable_bytes_used();
  ::caffe2::TwoNumberStatsProto* release_bytes_used();
  void set_allocated_bytes_used(::caffe2::TwoNumberStatsProto* bytes_used);

  // @@protoc_insertion_point(class_scope:caffe2.BlobProfile)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_bytes_used();
  inline void clear_has_bytes_used();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::caffe2::TwoNumberStatsProto* bytes_used_;
  friend void  protobuf_AddDesc_prof_5fdag_2eproto();
  friend void protobuf_AssignDesc_prof_5fdag_2eproto();
  friend void protobuf_ShutdownFile_prof_5fdag_2eproto();

  void InitAsDefaultInstance();
  static BlobProfile* default_instance_;
};
// -------------------------------------------------------------------

class ProfDAGProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe2.ProfDAGProto) */ {
 public:
  ProfDAGProto();
  virtual ~ProfDAGProto();

  ProfDAGProto(const ProfDAGProto& from);

  inline ProfDAGProto& operator=(const ProfDAGProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProfDAGProto& default_instance();

  void Swap(ProfDAGProto* other);

  // implements Message ----------------------------------------------

  inline ProfDAGProto* New() const { return New(NULL); }

  ProfDAGProto* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProfDAGProto& from);
  void MergeFrom(const ProfDAGProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ProfDAGProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required float mean = 2;
  bool has_mean() const;
  void clear_mean();
  static const int kMeanFieldNumber = 2;
  float mean() const;
  void set_mean(float value);

  // required float stddev = 3;
  bool has_stddev() const;
  void clear_stddev();
  static const int kStddevFieldNumber = 3;
  float stddev() const;
  void set_stddev(float value);

  // optional .caffe2.TwoNumberStatsProto execution_time = 4;
  bool has_execution_time() const;
  void clear_execution_time();
  static const int kExecutionTimeFieldNumber = 4;
  const ::caffe2::TwoNumberStatsProto& execution_time() const;
  ::caffe2::TwoNumberStatsProto* mutable_execution_time();
  ::caffe2::TwoNumberStatsProto* release_execution_time();
  void set_allocated_execution_time(::caffe2::TwoNumberStatsProto* execution_time);

  // repeated .caffe2.BlobProfile output_profile = 5;
  int output_profile_size() const;
  void clear_output_profile();
  static const int kOutputProfileFieldNumber = 5;
  const ::caffe2::BlobProfile& output_profile(int index) const;
  ::caffe2::BlobProfile* mutable_output_profile(int index);
  ::caffe2::BlobProfile* add_output_profile();
  ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >*
      mutable_output_profile();
  const ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >&
      output_profile() const;

  // @@protoc_insertion_point(class_scope:caffe2.ProfDAGProto)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_mean();
  inline void clear_has_mean();
  inline void set_has_stddev();
  inline void clear_has_stddev();
  inline void set_has_execution_time();
  inline void clear_has_execution_time();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  float mean_;
  float stddev_;
  ::caffe2::TwoNumberStatsProto* execution_time_;
  ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile > output_profile_;
  friend void  protobuf_AddDesc_prof_5fdag_2eproto();
  friend void protobuf_AssignDesc_prof_5fdag_2eproto();
  friend void protobuf_ShutdownFile_prof_5fdag_2eproto();

  void InitAsDefaultInstance();
  static ProfDAGProto* default_instance_;
};
// -------------------------------------------------------------------

class ProfDAGProtos : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe2.ProfDAGProtos) */ {
 public:
  ProfDAGProtos();
  virtual ~ProfDAGProtos();

  ProfDAGProtos(const ProfDAGProtos& from);

  inline ProfDAGProtos& operator=(const ProfDAGProtos& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProfDAGProtos& default_instance();

  void Swap(ProfDAGProtos* other);

  // implements Message ----------------------------------------------

  inline ProfDAGProtos* New() const { return New(NULL); }

  ProfDAGProtos* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProfDAGProtos& from);
  void MergeFrom(const ProfDAGProtos& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ProfDAGProtos* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .caffe2.ProfDAGProto stats = 1;
  int stats_size() const;
  void clear_stats();
  static const int kStatsFieldNumber = 1;
  const ::caffe2::ProfDAGProto& stats(int index) const;
  ::caffe2::ProfDAGProto* mutable_stats(int index);
  ::caffe2::ProfDAGProto* add_stats();
  ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >*
      mutable_stats();
  const ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >&
      stats() const;

  // optional string net_name = 2;
  bool has_net_name() const;
  void clear_net_name();
  static const int kNetNameFieldNumber = 2;
  const ::std::string& net_name() const;
  void set_net_name(const ::std::string& value);
  void set_net_name(const char* value);
  void set_net_name(const char* value, size_t size);
  ::std::string* mutable_net_name();
  ::std::string* release_net_name();
  void set_allocated_net_name(::std::string* net_name);

  // @@protoc_insertion_point(class_scope:caffe2.ProfDAGProtos)
 private:
  inline void set_has_net_name();
  inline void clear_has_net_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto > stats_;
  ::google::protobuf::internal::ArenaStringPtr net_name_;
  friend void  protobuf_AddDesc_prof_5fdag_2eproto();
  friend void protobuf_AssignDesc_prof_5fdag_2eproto();
  friend void protobuf_ShutdownFile_prof_5fdag_2eproto();

  void InitAsDefaultInstance();
  static ProfDAGProtos* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TwoNumberStatsProto

// optional float mean = 1;
inline bool TwoNumberStatsProto::has_mean() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TwoNumberStatsProto::set_has_mean() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TwoNumberStatsProto::clear_has_mean() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TwoNumberStatsProto::clear_mean() {
  mean_ = 0;
  clear_has_mean();
}
inline float TwoNumberStatsProto::mean() const {
  // @@protoc_insertion_point(field_get:caffe2.TwoNumberStatsProto.mean)
  return mean_;
}
inline void TwoNumberStatsProto::set_mean(float value) {
  set_has_mean();
  mean_ = value;
  // @@protoc_insertion_point(field_set:caffe2.TwoNumberStatsProto.mean)
}

// optional float stddev = 2;
inline bool TwoNumberStatsProto::has_stddev() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TwoNumberStatsProto::set_has_stddev() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TwoNumberStatsProto::clear_has_stddev() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TwoNumberStatsProto::clear_stddev() {
  stddev_ = 0;
  clear_has_stddev();
}
inline float TwoNumberStatsProto::stddev() const {
  // @@protoc_insertion_point(field_get:caffe2.TwoNumberStatsProto.stddev)
  return stddev_;
}
inline void TwoNumberStatsProto::set_stddev(float value) {
  set_has_stddev();
  stddev_ = value;
  // @@protoc_insertion_point(field_set:caffe2.TwoNumberStatsProto.stddev)
}

// optional int64 count = 3;
inline bool TwoNumberStatsProto::has_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TwoNumberStatsProto::set_has_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TwoNumberStatsProto::clear_has_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TwoNumberStatsProto::clear_count() {
  count_ = GOOGLE_LONGLONG(0);
  clear_has_count();
}
inline ::google::protobuf::int64 TwoNumberStatsProto::count() const {
  // @@protoc_insertion_point(field_get:caffe2.TwoNumberStatsProto.count)
  return count_;
}
inline void TwoNumberStatsProto::set_count(::google::protobuf::int64 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:caffe2.TwoNumberStatsProto.count)
}

// -------------------------------------------------------------------

// BlobProfile

// optional string name = 1;
inline bool BlobProfile::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BlobProfile::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BlobProfile::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BlobProfile::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& BlobProfile::name() const {
  // @@protoc_insertion_point(field_get:caffe2.BlobProfile.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BlobProfile::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:caffe2.BlobProfile.name)
}
inline void BlobProfile::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:caffe2.BlobProfile.name)
}
inline void BlobProfile::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:caffe2.BlobProfile.name)
}
inline ::std::string* BlobProfile::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:caffe2.BlobProfile.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BlobProfile::release_name() {
  // @@protoc_insertion_point(field_release:caffe2.BlobProfile.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BlobProfile::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:caffe2.BlobProfile.name)
}

// optional .caffe2.TwoNumberStatsProto bytes_used = 3;
inline bool BlobProfile::has_bytes_used() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BlobProfile::set_has_bytes_used() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BlobProfile::clear_has_bytes_used() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BlobProfile::clear_bytes_used() {
  if (bytes_used_ != NULL) bytes_used_->::caffe2::TwoNumberStatsProto::Clear();
  clear_has_bytes_used();
}
inline const ::caffe2::TwoNumberStatsProto& BlobProfile::bytes_used() const {
  // @@protoc_insertion_point(field_get:caffe2.BlobProfile.bytes_used)
  return bytes_used_ != NULL ? *bytes_used_ : *default_instance_->bytes_used_;
}
inline ::caffe2::TwoNumberStatsProto* BlobProfile::mutable_bytes_used() {
  set_has_bytes_used();
  if (bytes_used_ == NULL) {
    bytes_used_ = new ::caffe2::TwoNumberStatsProto;
  }
  // @@protoc_insertion_point(field_mutable:caffe2.BlobProfile.bytes_used)
  return bytes_used_;
}
inline ::caffe2::TwoNumberStatsProto* BlobProfile::release_bytes_used() {
  // @@protoc_insertion_point(field_release:caffe2.BlobProfile.bytes_used)
  clear_has_bytes_used();
  ::caffe2::TwoNumberStatsProto* temp = bytes_used_;
  bytes_used_ = NULL;
  return temp;
}
inline void BlobProfile::set_allocated_bytes_used(::caffe2::TwoNumberStatsProto* bytes_used) {
  delete bytes_used_;
  bytes_used_ = bytes_used;
  if (bytes_used) {
    set_has_bytes_used();
  } else {
    clear_has_bytes_used();
  }
  // @@protoc_insertion_point(field_set_allocated:caffe2.BlobProfile.bytes_used)
}

// -------------------------------------------------------------------

// ProfDAGProto

// required string name = 1;
inline bool ProfDAGProto::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProfDAGProto::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProfDAGProto::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProfDAGProto::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& ProfDAGProto::name() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProfDAGProto::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.name)
}
inline void ProfDAGProto::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:caffe2.ProfDAGProto.name)
}
inline void ProfDAGProto::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:caffe2.ProfDAGProto.name)
}
inline ::std::string* ProfDAGProto::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProfDAGProto::release_name() {
  // @@protoc_insertion_point(field_release:caffe2.ProfDAGProto.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProfDAGProto::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:caffe2.ProfDAGProto.name)
}

// required float mean = 2;
inline bool ProfDAGProto::has_mean() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProfDAGProto::set_has_mean() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProfDAGProto::clear_has_mean() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProfDAGProto::clear_mean() {
  mean_ = 0;
  clear_has_mean();
}
inline float ProfDAGProto::mean() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.mean)
  return mean_;
}
inline void ProfDAGProto::set_mean(float value) {
  set_has_mean();
  mean_ = value;
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.mean)
}

// required float stddev = 3;
inline bool ProfDAGProto::has_stddev() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProfDAGProto::set_has_stddev() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProfDAGProto::clear_has_stddev() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProfDAGProto::clear_stddev() {
  stddev_ = 0;
  clear_has_stddev();
}
inline float ProfDAGProto::stddev() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.stddev)
  return stddev_;
}
inline void ProfDAGProto::set_stddev(float value) {
  set_has_stddev();
  stddev_ = value;
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.stddev)
}

// optional .caffe2.TwoNumberStatsProto execution_time = 4;
inline bool ProfDAGProto::has_execution_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProfDAGProto::set_has_execution_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProfDAGProto::clear_has_execution_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProfDAGProto::clear_execution_time() {
  if (execution_time_ != NULL) execution_time_->::caffe2::TwoNumberStatsProto::Clear();
  clear_has_execution_time();
}
inline const ::caffe2::TwoNumberStatsProto& ProfDAGProto::execution_time() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.execution_time)
  return execution_time_ != NULL ? *execution_time_ : *default_instance_->execution_time_;
}
inline ::caffe2::TwoNumberStatsProto* ProfDAGProto::mutable_execution_time() {
  set_has_execution_time();
  if (execution_time_ == NULL) {
    execution_time_ = new ::caffe2::TwoNumberStatsProto;
  }
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.execution_time)
  return execution_time_;
}
inline ::caffe2::TwoNumberStatsProto* ProfDAGProto::release_execution_time() {
  // @@protoc_insertion_point(field_release:caffe2.ProfDAGProto.execution_time)
  clear_has_execution_time();
  ::caffe2::TwoNumberStatsProto* temp = execution_time_;
  execution_time_ = NULL;
  return temp;
}
inline void ProfDAGProto::set_allocated_execution_time(::caffe2::TwoNumberStatsProto* execution_time) {
  delete execution_time_;
  execution_time_ = execution_time;
  if (execution_time) {
    set_has_execution_time();
  } else {
    clear_has_execution_time();
  }
  // @@protoc_insertion_point(field_set_allocated:caffe2.ProfDAGProto.execution_time)
}

// repeated .caffe2.BlobProfile output_profile = 5;
inline int ProfDAGProto::output_profile_size() const {
  return output_profile_.size();
}
inline void ProfDAGProto::clear_output_profile() {
  output_profile_.Clear();
}
inline const ::caffe2::BlobProfile& ProfDAGProto::output_profile(int index) const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.output_profile)
  return output_profile_.Get(index);
}
inline ::caffe2::BlobProfile* ProfDAGProto::mutable_output_profile(int index) {
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.output_profile)
  return output_profile_.Mutable(index);
}
inline ::caffe2::BlobProfile* ProfDAGProto::add_output_profile() {
  // @@protoc_insertion_point(field_add:caffe2.ProfDAGProto.output_profile)
  return output_profile_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >*
ProfDAGProto::mutable_output_profile() {
  // @@protoc_insertion_point(field_mutable_list:caffe2.ProfDAGProto.output_profile)
  return &output_profile_;
}
inline const ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >&
ProfDAGProto::output_profile() const {
  // @@protoc_insertion_point(field_list:caffe2.ProfDAGProto.output_profile)
  return output_profile_;
}

// -------------------------------------------------------------------

// ProfDAGProtos

// repeated .caffe2.ProfDAGProto stats = 1;
inline int ProfDAGProtos::stats_size() const {
  return stats_.size();
}
inline void ProfDAGProtos::clear_stats() {
  stats_.Clear();
}
inline const ::caffe2::ProfDAGProto& ProfDAGProtos::stats(int index) const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProtos.stats)
  return stats_.Get(index);
}
inline ::caffe2::ProfDAGProto* ProfDAGProtos::mutable_stats(int index) {
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProtos.stats)
  return stats_.Mutable(index);
}
inline ::caffe2::ProfDAGProto* ProfDAGProtos::add_stats() {
  // @@protoc_insertion_point(field_add:caffe2.ProfDAGProtos.stats)
  return stats_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >*
ProfDAGProtos::mutable_stats() {
  // @@protoc_insertion_point(field_mutable_list:caffe2.ProfDAGProtos.stats)
  return &stats_;
}
inline const ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >&
ProfDAGProtos::stats() const {
  // @@protoc_insertion_point(field_list:caffe2.ProfDAGProtos.stats)
  return stats_;
}

// optional string net_name = 2;
inline bool ProfDAGProtos::has_net_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProfDAGProtos::set_has_net_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProfDAGProtos::clear_has_net_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProfDAGProtos::clear_net_name() {
  net_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_net_name();
}
inline const ::std::string& ProfDAGProtos::net_name() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProtos.net_name)
  return net_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProfDAGProtos::set_net_name(const ::std::string& value) {
  set_has_net_name();
  net_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProtos.net_name)
}
inline void ProfDAGProtos::set_net_name(const char* value) {
  set_has_net_name();
  net_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:caffe2.ProfDAGProtos.net_name)
}
inline void ProfDAGProtos::set_net_name(const char* value, size_t size) {
  set_has_net_name();
  net_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:caffe2.ProfDAGProtos.net_name)
}
inline ::std::string* ProfDAGProtos::mutable_net_name() {
  set_has_net_name();
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProtos.net_name)
  return net_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProfDAGProtos::release_net_name() {
  // @@protoc_insertion_point(field_release:caffe2.ProfDAGProtos.net_name)
  clear_has_net_name();
  return net_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProfDAGProtos::set_allocated_net_name(::std::string* net_name) {
  if (net_name != NULL) {
    set_has_net_name();
  } else {
    clear_has_net_name();
  }
  net_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), net_name);
  // @@protoc_insertion_point(field_set_allocated:caffe2.ProfDAGProtos.net_name)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace caffe2

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_prof_5fdag_2eproto__INCLUDED
